# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capact < Formula
  desc ""
  homepage "https://github.com/mkuziemko/homebrew-tap"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkuziemko/capact/releases/download/v0.5.1/capact-darwin-amd64"
      sha256 "b25d2b1df17365933a1497bf557d2c0298abf298bd1b1121749f8f1f06b2512d"

      def install
        bin.install "capact-darwin-amd64" => "capact-darwin-amd64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkuziemko/capact/releases/download/v0.5.1/capact-darwin-arm64"
      sha256 "6b2d71753e248bb1bba9ec7804d34d75ee214dae0100ba0fd40456212a903d72"

      def install
        bin.install "capact-darwin-arm64" => "capact-darwin-arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkuziemko/capact/releases/download/v0.5.1/capact-linux-arm64"
      sha256 "d2f1b9c9d49989c02955cac8fd7efa9e44e1bb8964155ee9a0265ce5160d8d9b"

      def install
        bin.install "capact-linux-arm64" => "capact-linux-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mkuziemko/capact/releases/download/v0.5.1/capact-linux-amd64"
      sha256 "b883f3f9b135e5dac9fc54f9ad75d685decdd2d12d9dc162ee99e5a757e772f7"

      def install
        bin.install "capact-linux-amd64" => "capact-linux-amd64"
      end
    end
  end
end
