# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Populator < Formula
  desc ""
  homepage "https://github.com/mkuziemko/homebrew-tap"
  version "0.5.2"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkuziemko/capact/releases/download/v0.5.2/populator_0.5.2_linux_arm64"
      sha256 "ff2e4ac83b4fcc81ccd84e3ab7786d4c7e7114b0783596558841e13cf3a20a64"

      def install
        bin.install "populator_0.5.2_linux_arm64" => "populator"
      end
    end
  end
end
